openapi: 3.0.1
info:
  title: CartAPI
  description: API Definition of CartAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/cart
paths:
  /get-cart/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /add-cart:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /delete-cart/{id}:
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
