openapi: 3.0.1
info:
  title: ReservationAPI
  description: API Definition of ReservationAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/reservation
paths:
  /get-reservation:
    get:
      responses:
        default:
          description: Default response
  /get-reservation/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /get-adminreservation/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /add-reservation:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /update-reservation/{id}:
    put:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /delete-reservation/{id}:
    delete:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
